apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kubernetes-b050"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kubernetes-b050"
  template:
    metadata:
      labels:
        app: "kubernetes-b050"
    spec:
      containers:
        - name: "kubernetes-b050"
          image: "dockerregg.azurecr.io/kubernetes"
          ports:
          - containerPort: 8080