on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: dockerregg.azurecr.io
        username: ${{ secrets.acr_dockerregg_username }}
        password: ${{ secrets.acr_dockerregg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "DockerFile" -t dockerregg.azurecr.io/kubernetes:${{ github.sha }} --label dockerfile-path=DockerFile
        docker push dockerregg.azurecr.io/kubernetes:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubernetes_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ingress-nginx | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ingress-nginx`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ingress-nginx
        container-registry-url: dockerregg.azurecr.io
        container-registry-username: ${{ secrets.acr_dockerregg_username }}
        container-registry-password: ${{ secrets.acr_dockerregg_password }}
        secret-name: kubernetesdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ingress-nginx
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          dockerregg.azurecr.io/kubernetes:${{ github.sha }}
        imagepullsecrets: |
          kubernetesdockerauth
